#!/bin/sh
set -e

# Writes version constants to the path given as $1. Defaults to
# src/cli/version.rs for direct/manual invocation; build.rs passes an
# $OUT_DIR path so the file lands in build output.
out="${1:-src/cli/version.rs}"

head=`git rev-parse HEAD`
branch=`git rev-parse --abbrev-ref HEAD`
date=`date`

{
    echo "// auto generated by version.sh"
    echo "pub const GIT_VERSION: &str = \"$head\";"
    echo "pub const GIT_BRANCH: &str = \"$branch\";"
    echo "pub const BUILD_TIME: &str = \"$date\";"
} > "$out"
