- name: demo external module feature
  groups: 
    - all
  vars:
    b: 20
  
  tasks:

  # NOTE: this feature is in development for release 0.2 and is not complete at this time

    - !external  
      use: demo_external.py
      params:
         a: 1
         b: "{{ b }}"
         c: [ "foo", "bar", "baz"]
      save: result
      # failed_when: (lt sum 50)
      # changed_when: (lt sum 50)
      # changed_when: false

    - !debug
      vars: 
        - result




  