// auto generated by version.sh
pub const GIT_VERSION: &str = "b8feba329e6c5ad123c9291d67f0eb6c95a5c730";
pub const GIT_BRANCH: &str = "fix/clippy-cleanup";
pub const BUILD_TIME: &str = "Thu 18 Jun 05:14:33 BST 2026";
